---
- name: Create directory structure
  hosts: localhost
  tasks:
  - file:
      name: configs
      state: directory

- name: Create device configurations
  hosts: all
  tasks:
  - template:
      src: ios-config.j2
      dest: "configs/{{inventory_hostname}}.cfg"
    delegate_to: localhost
